hanaka`s mod søknad :)

 1. What is your Twitch username?: hanaka14
 2. what is your name?: Jahn-Aage
 3. How old are you?: 15
 4. Are you or have you been a Mod in another Twitch channel?: ja goli og en som heter norwegionpig og fusixplays og mange andre.
 5. How can you help hofa by being a Mod of his channel?: jeg følger godt med i chat og er snill + jeg tar de som bryter reglene sån at  
    hofa kan streame uten og bry seg om regel brytere og jeg kan hjelpe med og sette op streams og fikse bugs på streamen :)
